AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates a new ECR Repository
Parameters:
  RepositoryName:
    Type: String
    Default: ecrrepo
    Description: A name for the ECR repository
  EnvironmentName:
    Type: String
    Default: MyApplicationDev
    Description: A name for the environment that this cloudformation will be part of.
                 Used to locate other resources in the same environment.
 
Resources:
  MyRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Ref 'RepositoryName'
      RepositoryPolicyText:
        Version: 2008-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - Fn::ImportValue:
                    !Join [':', [!Ref 'EnvironmentName', 'ECSRole']]
            Action:
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:PutImage'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:UploadLayerPart'
              - 'ecr:CompleteLayerUpload'
Outputs:
  ECSRepository:
    Value: !Ref MyRepository
